apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-tag
  template:
    metadata:
      labels:
        app: demo-tag
    spec:
      containers:
        - name: demo-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
