#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: demo-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#spec:
#  rules:
#    - host: {{ .Values.ingress.host }}
#      http:
#        paths:
#          - path: /?(.*)
#            backend:
#              serviceName: demo-server
#              servicePort: {{ .Values.service.port }}