kind: Service
apiVersion: v1
metadata:
  name: demo-server
spec:
  selector:
    app: demo-tag
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: restport
    - protocol: TCP
      port: 5701
      targetPort: hazelcast
      name: hzport
