apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Values.service.name.rest }}
  selector:
    matchLabels:
      app: demo-tag
  template:
    metadata:
      labels:
        app: demo-tag
    spec:
      containers:
        - name: demo-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              memory: {{ .Values.resourceLimits.small.memory }}
              cpu: {{ .Values.resourceLimits.small.cpu }}
            limits:
              memory: {{ .Values.resourceLimits.large.memory }}
              cpu: {{ .Values.resourceLimits.large.cpu }}