replicaCount: 0
#
resourceLimits:
  small:
    memory: "64Mi"
    cpu: "200m"
  medium:
    memory: "128Mi"
    cpu: "350m"
  large:
    memory: "256Mi"
    cpu: "500m"
#
statefulset:
  name: demo
image:
  repository: mityi/sample-hz-arm
  tag: 0.0.3
#
service:
  name:
    hz: hz-service-name
    rest: demo-server
  type:
    lb: LoadBalancer
  port: 8080
#
ingress:
  host: te.nsk.ru
